name: CI

on:
  pull_request:
  push: {branches-ignore: ["**_pr"]}

jobs:

  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        poetry-min: ["", "poetry-min"]
        exclude:
          - {os: windows-latest, python: "3.6"}
    runs-on: "${{ matrix.os }}"
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Overwrite pyproject.toml and poetry.lock
        if: matrix.poetry-min
        run: |
          cp -v pyproject-min.toml pyproject.toml
          cp -v poetry-min.lock poetry.lock
          git diff --color

      - name: Initialize dependencies
        uses: Robpol86/actions-init-deps-py@v3
        with:
          cache-buster: "${{ join(matrix.*, '|') }}"
          python-version: "${{ matrix.python }}"

      - name: Run tests
        env:
          PY_COLORS: 1
        run: make test

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          name: "coverage-${{ runner.os }}-${{ join(matrix.*, '|') }}"

      - name: Run lints
        run: make lint

      - name: Run integration tests
        run: make it

      - name: Build docs
        run: make docs

      - name: Build package
        run: |
          make build
          cd dist
          unzip -t *.whl
          unzip -p *.whl '*/METADATA'
