name: PyPI

on:
  release: {types: [published]}

jobs:

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - {name: Check out repository code, uses: actions/checkout@v2}
      - {name: Initialize dependencies, id: init, uses: Robpol86/actions-init-deps-py@v3}
      - {name: Build docs, run: make docs}
      - {name: Compress, run: tar -C docs/_build -czvf docs.tar.gz --transform s/^html/docs/ html/}
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with: {name: docs, path: docs.tar.gz, if-no-files-found: error}

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - {name: Check out repository code, uses: actions/checkout@v2}
      - {name: Initialize dependencies, id: init, uses: Robpol86/actions-init-deps-py@v3, with: {no-dev: "true"}}
      - {name: Copy LICENSE to COPYING, run: cp --no-clobber --verbose LICENSE COPYING}  # For Python wheel.
      - {name: Build package, run: make build}
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with: {name: dist, path: dist/, if-no-files-found: error}

  publish:
    name: Publish to PyPI
    needs: [build, docs]
    runs-on: ubuntu-latest
    steps:
      - {name: Fetch packages, uses: actions/download-artifact@v2, with: {name: dist, path: dist}}
      - name: Publish packages to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Fetch docs
        uses: actions/download-artifact@v2
        with: {name: docs, path: dist}
      - name: Upload artifacts to Release
        uses: svenstaro/upload-release-action@v2
        with: {file: dist/*, file_glob: true, repo_token: "${{ secrets.GITHUB_TOKEN }}", tag: "${{ github.ref }}"}
